type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "SJTU Top Cybersecurity Student Scholarship"
subtitle = "Top 3%"
date = "2022"
content = ""

[[items]]
title = "SJTU Outstanding Undergraduate Scholarship"
subtitle = "Top 15%, 3× recipient"
date = "2020,21,22"
content = ""

[[items]]
title = "Mathematical Contest in Modeling - Meritorious"
date = "2021-04"

[[items]]
title = "Mathematical Contest in Modeling - Honorable Mention"
date = "2020-04"

[[items]]
title = "Shanghai Jiao Tong University Merit Student"
date = "2020-04"
