type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "Top Cybersecurity Student Scholarship"
subtitle = "Shanghai Jiao Tong University"
date = "2022"
content = "Top 3% - Nov 2022"

[[items]]
title = "Outstanding Undergraduate Scholarship"
subtitle = "Shanghai Jiao Tong University"
date = "2020-2022"
content = "Top 15%, 3× recipient - Nov 2020-2022"

[[items]]
title = "Mathematical Contest in Modeling - Meritorious"
subtitle = "MCM"
date = "2021"
content = "Apr 2021"

[[items]]
title = "Mathematical Contest in Modeling - Honorable Mention"
subtitle = "MCM"
date = "2020"
content = "Apr 2020"

[[items]]
title = "Merit Student"
subtitle = "Shanghai Jiao Tong University"
date = "2020"
content = "Apr 2020"
