[site]
title = "Yang Fei (费扬)"
description = "PhD student at NUS. Coding for Something... Or Nothing."
favicon = "/fy_favicon.png"
last_updated = "June 15, 2026"

[author]
name = "Yang Fei"
title = "1st-year PhD"
institution = "National University of Singapore"
avatar = "/fy_avatar.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "yfei11@u.nus.edu"
location = "Singapore"
location_url = "https://maps.google.com/maps/place/Singapore"
location_details = [
  "21 Lower Kent Ridge Rd,",
  "Singapore 119077"
]
google_scholar = "https://scholar.google.com/citations?user=ZnShSQwAAAAJ&hl=en"
orcid = ""
github = "https://github.com/2020dfff"
linkedin = "https://www.linkedin.com/in/2022dfff"
twitter = "https://twitter.com/Faye2020D"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Research"
type = "page"
target = "research"
href = "/research"

[[navigation]]
title = "Internships"
type = "page"
target = "internships"
href = "/internships"

[[navigation]]
title = "Projects"
type = "page"
target = "projects"
href = "/projects"

[[navigation]]
title = "Education"
type = "page"
target = "education"
href = "/education"

[[navigation]]
title = "Misc"
type = "page"
target = "misc"
href = "/misc"

[[navigation]]
title = "Blog"
type = "page"
target = "blog"
href = "/blog"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
