type = "card"
title = "Internships"
description = "My internship experiences"

[[items]]
title = "Shanghai Artificial Intelligence Laboratory"
subtitle = "AI Researcher"
date = "Jun 2024 - Dec 2024"
content = "Conduct research on AI Application in Urban Computing fields like traffic and society. Develop a LLM-powered MAS platform which adapt its organization in various task scenarios."
logo = "/images/ailab-logo.png"

[[items]]
title = "HUAWEI ICT Department"
subtitle = "Software Development Engineer"
date = "Aug 2022 - Oct 2022"
content = "Interned in packet core network department, ddb group, focus on distributed database microservices built on cloud core. Provide a full range of core network software, help operators build an agile and reliable core network. Build DDB micro-service based on Go Cell framework, realize synchronous data processing."
logo = "/images/huawei-logo.svg"
