[[news]]
date = "2025-04"
content = "🎉 Our paper accepted by SIGIR'25!"

[[news]]
date = "2025-03"
content = "🎉 NUS 25Fall PhD offer, New journey!"

[[news]]
date = "2024-05"
content = "🎉 Started a new Internship at Shanghai AI Lab!"

[[news]]
date = "2023-08"
content = "🎓 Started my master journey at NUS SoC!"

[[news]]
date = "2023-06"
content = "🎓 Graduated from SJTU with outstanding graduate award!"
